stages: 
- build
- deploy

variables:
DOCKER_DRIVER: overlay2
REPOSITORIO: "https://github.com/manoluky/Framework_automatizacion.git"
RAMA: "master"
TAG: "@TEST_PX-3"
TIPO: 0
build: 
image: docker:latest
services:
- docker:dind
stage: build
script:
- echo $REPOSITORIO
- echo $TAG
- docker login -u "$CI_REGISTRY_USER" -p "$CI_REGISTRY_PASSWORD" $CI_REGISTRY
- docker pull scl.ocir.io/ax8y1uprz5rs/devsecops/factoriadevops/calidad:pruebasautomatizadas_1.0
- docker run -e REPOSITORIO=https://github.com/manoluky/Framework_automatizacion.git -e RAMA=master -e TAG=@TEST_PX-3 -e TIPO=0
